### ISSUE TITLE
Tiny Render Size

### ISSUE THREAD

**Issue by felixroos** [Marr11317/Bb#2]
Hello!

This library looks promising, but trying out the example code, i get a really tiny pixelated output:

![screenshot](https://i.imgur.com/ENdQFAa.png)

I tried changing the canvas & font size + searched for size / scaling options in `BbChordSymbolOptions`, but could not find anything.

I pasted my code into a little [codesandbox](https://codesandbox.io/s/bb-chord-symbol-test-jp2ej)

Is there something I am missing? Maybe I need to use the Petaluma Font?

**Comment by felixroos** [comment]
I found the solution in [this component](https://github.com/no-chris/chord-symbol-demo/tree/main/src/components/showcase/CanvasRenderer), see the [updated sandbox](https://codesandbox.io/s/bb-chord-symbol-test-forked-70i5b?file=/src/ChordSymbol.js). Cool! Would be nice if the readme would give some hints. Anyway cool stuff, thanks! I will definitely add this to the new version of my [web based backing track player](https://felixroos.github.io/jazzband/)!

**Comment by ecstrema** [comment]
Great to hear you managed to make it work! There was indeed some translations needed that I did not document. The goal would ideally be for your first sample to work, since it's the what I wanted, but I stopped working on this library a while ago. Tell me if you encounter any other problem! Meanwhile, I'll update the readme.

**Comment by Marr11317** [comment]
Also, that repo was for when I was experimenting for monorepos, but the official standalone repo for the library is here: https://github.com/Marr11317/bb-format

**Comment by ecstrema** [comment]
For your jazzband backing track player, you might be interested in that example: https://github.com/Marr11317/Bb/blob/master/packages/format/img/GiantSteps.png
The source code for that is in an other repo: https://github.com/Marr11317/bb-format/tree/master/demo.

Sorry, yes everything is quite messed up now ;)
